{
 "title": "Scenario B",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "wind",
     "query": "SELECT mean(\"wind_speed\") FROM \"mqtt_consumer\" WHERE topic =~ /.*weather.*/ AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Trap Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "SELECT mean(\"trap_count\") FROM \"mqtt_consumer\" WHERE topic =~ /.*weather.*/ AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Nebulizer",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": " ",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\" WHERE (\"topic\"::tag = 'oliveto/sector_a/nebulizer') AND $timeFilter"
    }
   ]
  }
 ]
}